### PR TITLE
Fix `argon2` with special case

### LINKED ISSUE #45: Add support for `argon2`
This integration test fails:

```js
const argon2 = require('argon2');
console.log('argon is ' + typeof argon2);
```

### Error

```
/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-2963026860021942/node_modules/node-gyp-build/index.js:56
  throw new Error('No native build was found for ' + target)
  ^

Error: No native build was found for platform=darwin arch=x64 runtime=node abi=64 uv=1 libc=glibc
    at Function.load.path (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-2963026860021942/node_modules/node-gyp-build/index.js:56:9)
    at load (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-2963026860021942/node_modules/node-gyp-build/index.js:20:30)
    at Object.<anonymous> (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-2963026860021942/node_modules/argon2/argon2.js:5:81)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

Related to https://github.com/zeit/now-builders/issues/929

This is likely an issue with argon2's dependency [node-gyp-build](https://www.npmjs.com/package/node-gyp-build) which will likely have to be special cased.

### PR DESCRIPTION
**Pull request by styfle**
Fixes #45

This package doesn't seem to work on Windows so I excluded from the Windows CI.

### CODE REVIEW

**Comment by styfle** [comment]
@lucleray This package doesn't seem to work on Windows so I excluded from the Windows CI.

**Comment by styfle** [comment]
@lucleray It turns out that Linux and Mac needed different binary paths so I included both.

**Comment by ranisalt** [comment]
Hi! I'm the maintainer for Argon2. What do you mean that it does not work on Windows? We have had CI running on Windows for a while with no issues, and while some users report errors on compilation, it's usually due to missing build tools. Could you elaborate so we can fix it?

**Comment by styfle** [comment]
Hi @ranisalt 

The commits above have the CI results from GitHub Actions.

Take a look at this one https://github.com/zeit/node-file-trace/runs/198427474

**Comment by ranisalt** [comment]
node-gyp output is horribly awful, but from
`gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT` I think that Actions doesn't have VS build tools installed. You can see from the [list of available software](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#windows-server-2019), I don't recognize anything there for compiling C++.

**Comment by styfle** [comment]
That's strange because the linked document says it contains `cmake.exe` and `MinGW` 🤷‍♂ 

Is this something that needs to be reported to the GH Actions team or do we need to install something in CI before building?

**Comment by ranisalt** [comment]
Honestly I don't know, my builds on Windows are failing too. We have Appveyor working but there you can pick a Visual Studio version and it installs all components, compilers included. Maybe on Windows we can override compiler location with an environment variable, but I have no clue how.

**Pull request merged**
