### PR TITLE
Refactor realpath handling

### PR DESCRIPTION
**Pull request by guybedford**
This refactors the realpath handling to apply to all file emissions (including assets).

This is done by lowering the realpath operation onto `job`, including the way it emits the symlink junctions.

### CODE REVIEW

**Comment by styfle** [comment]
@guybedford How about tests?

**Comment by guybedford** [comment]
Sure, I've included a test.

**Comment by lucleray** [comment]
@guybedford Have you considered doing `fs.realpath` on the path, and if realpath <> path, find their common part, which would tell you where the symlink is? Maybe your method is more reliable and faster?

**Comment by guybedford** [comment]
Yes that sounds like it would work. The benefit of this approach is being
able the share the real path cache though.

**Pull request merged**
