### PR TITLE
Paths implementation

### PR DESCRIPTION
**Pull request by guybedford**
This implements a simple paths implementation for easier integration into other workflows.

We could also implement a full resolve hook option here as well, but this seemed somewhat simpler for now.

### CODE REVIEW

**Comment by guybedford** [comment]
Just working on adjustment to this to ensure compatibility with node_modules resolution.

**Comment by guybedford** [comment]
Directly supporting tsconfig.json `baseUrl` configuration could be an alternative but I must admit I'm not a fan of this resolution mechanism as no runtimes really support this sort of resolution apart from just the old AMD loaders.

Paths as written here more closely follows the import maps style of declaration, as opposed to the older AMD approach. I've also moved the paths application to happen after node_modules resolution so it behaves as a fallback for compatibility.

An alternative could be to make this configuration exactly like the ts baseUrl configuration, and then later as a follow up that could enable automatically inferring this.

I'm open to either approach though.

**Comment by styfle** [comment]
There is a longstanding feature request (even back from ncc) to support TS `paths` (#85).

Even if it's non-standard, we should provide a way for `@now/node` to convert TS paths to NFT paths.

The alternative is waiting another year or more to TS to support import maps (I'm not even sure if Node.js supports import maps yet).

**Comment by guybedford** [comment]
@styfle it's no problem if we want to change it to align with ts paths. The main priority was to get the simplest approach working for the API usage (and avoid forking there), but I'm certainly not tied to this API.

**Comment by styfle** [comment]
@guybedford I like the idea of aligning NFT with Node, but I'm not sure how to convert TS [paths](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) to this format considering TS supports an array on the right hand side.

```js
{
  "compilerOptions": {
     // This must be specified if "paths" is
    "baseUrl": ".",
    "paths": {
       // This mapping is relative to "baseUrl" and can have fallbacks
      "jquery": ["node_modules/jquery/slim", "node_modules/jquery/all"]
    }
  }
}
```

How would you write that with NFT?

**Comment by guybedford** [comment]
@styfle supporting array paths here sounds like a worthy feature to me.

**Pull request merged**
